# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: ecvphdevsmich
# "service" is the name of this project. This will also be added to your AWS resource names.
service: python-serverless-mich

provider:
  name: aws
  runtime: python3.12
  role: arn:aws:iam::874957933250:role/serverless-app-role
  region: us-east-2

functions:
  hello:
    name: ${env:FUNC_PREFIX}-hello
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getAllProducts:
    name: ${env:FUNC_PREFIX}-getAllProducts
    handler: handler.get_all_products
    events:
      - httpApi:
          path: /products
          method: get

  createOneProduct:
    name: ${env:FUNC_PREFIX}-createOneProduct
    handler: handler.create_one_product
    events:
      - httpApi:
          path: /products
          method: post

  getOneProduct:
    name: ${env:FUNC_PREFIX}-getOneProduct
    handler: handler.get_one_product
    events:
      - httpApi:
          path: /products/{product_id}
          method: get

  deleteOneProduct:
    name: ${env:FUNC_PREFIX}-deleteOneProduct
    handler: handler.delete_one_product
    events:
      - httpApi:
          path: /products/{product_id}
          method: delete
  
  updateOneProduct:
    name: ${env:FUNC_PREFIX}-updateOneProduct
    handler: handler.update_one_product
    events:
      - httpApi:
          path: /products/{product_id}
          method: put

  addStocksToProduct:
    name: ${env:FUNC_PREFIX}-addStocksToProduct
    handler: handler.add_stocks_to_product
    events:
      - httpApi:
          path: /products/{product_id}/stocks
          method: post

  batchCreateProducts:
    name: ${env:FUNC_PREFIX}-batchCreateProducts
    handler: handler.batch_create_products
    events:
      - s3:
          bucket: products-s3bucket-mich
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_create/
          existing: true

  batchDeleteProducts:
    name: ${env:FUNC_PREFIX}-batchDeleteProducts
    handler: handler.batch_delete_products
    events:
      - s3:
          bucket: products-s3bucket-mich
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_delete/
          existing: true

  receiveMessagesFromSqs:
    name: ${env:FUNC_PREFIX}-receiveMessagesFromSqs
    handler: handler.receive_message_from_sqs
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ProductsQueue
              - Arn

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable_mich
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: Dev

    ProductInventory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductInventory_mich
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
          - AttributeName: datetime
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
          - AttributeName: datetime
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: Dev

    ProductsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: products-queue-mich-sqs-v2
        VisibilityTimeout: 120  # Timeout in seconds
        MessageRetentionPeriod: 1209600  # Retain messages for 14 days

