# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: ecvphdevsmich
# "service" is the name of this project. This will also be added to your AWS resource names.
service: python-serverless-mich

provider:
  name: aws
  runtime: python3.12
  role: arn:aws:iam::874957933250:role/serverless-app-role
  region: us-east-2
  environment:
    PRODUCTS_TABLE_NAME: ProductsTable_mich


functions:
  hellseo:
    name: ${env:FUNC_PREFIX}-hello
    handler: app.handlers.product_handler.hello
    timeout: 30
    events:
      - httpApi:
          path: /
          method: get
  getAllProducts:
    name: ${env:FUNC_PREFIX}-getAllProducts
    handler: app.handlers.product_handler.get_all_products
    timeout: 30
    events:
      - httpApi:
          path: /products
          method: get

  createOneProduct:
    name: ${env:FUNC_PREFIX}-createOneProduct
    handler: app.handlers.product_handler.create_one_product
    timeout: 30
    events:
      - httpApi:
          path: /products
          method: post

  getOneProduct:
    name: ${env:FUNC_PREFIX}-getOneProduct
    handler: app.handlers.product_handler.get_one_product
    timeout: 30
    events:
      - httpApi:
          path: /products/{product_id}
          method: get

  deleteOneProduct:
    name: ${env:FUNC_PREFIX}-deleteOneProduct
    handler: app.handlers.product_handler.delete_one_product
    timeout: 30
    events:
      - httpApi:
          path: /products/{product_id}
          method: delete
  
  updateOneProduct:
    name: ${env:FUNC_PREFIX}-updateOneProduct
    handler: app.handlers.product_handler.update_one_product
    timeout: 30
    events:
      - httpApi:
          path: /products/{product_id}
          method: put

  addStocksToProduct:
    name: ${env:FUNC_PREFIX}-addStocksToProduct
    handler: app.handlers.product_handler.add_stocks_to_product
    timeout: 30
    events:
      - httpApi:
          path: /products/{product_id}/stocks
          method: post

  batchCreateProducts:
    name: ${env:FUNC_PREFIX}-batchCreateProducts
    handler: app.handlers.product_handler.batch_create_products
    timeout: 30
    events:
      - s3:
          bucket: products-s3bucket-mich
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_create/
          existing: true

  batchDeleteProducts:
    name: ${env:FUNC_PREFIX}-batchDeleteProducts
    handler: app.handlers.product_handler.batch_delete_products
    timeout: 30
    events:
      - s3:
          bucket: products-s3bucket-mich
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_delete/
          existing: true

  receiveMessagesFromSqs:
    name: ${env:FUNC_PREFIX}-receiveMessagesFromSqs
    handler: app.handlers.product_handler.receive_message_from_sqs
    timeout: 30
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ProductsQueue
              - Arn

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable_mich
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: Dev

    ProductInventory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductInventory_mich
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
          - AttributeName: datetime
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
          - AttributeName: datetime
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: Dev

    ProductsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: products-queue-mich-sqs-v2
        VisibilityTimeout: 120  # Timeout in seconds
        MessageRetentionPeriod: 1209600  # Retain messages for 14 days

package:
  exclude:
    - .serverless/**
    - env/**
    - build/**
    - dist/**
    - "*.egg-info/**"

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3  # Keep the 3 most recent versions
